# Generated by Django 2.1.3 on 2018-11-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsiteminstance',
            name='url',
            field=models.URLField(blank=True, max_length=510),
        ),
    ]
