# Generated by Django 3.0.8 on 2020-07-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiny", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="company", name="date_last_updated",),
        migrations.RemoveField(model_name="concept", name="date_last_updated",),
        migrations.RemoveField(model_name="franchise", name="date_last_updated",),
        migrations.RemoveField(model_name="game", name="date_last_updated",),
        migrations.RemoveField(model_name="genre", name="date_last_updated",),
        migrations.RemoveField(model_name="platform", name="date_last_updated",),
        migrations.RemoveField(model_name="rating", name="date_last_updated",),
        migrations.RemoveField(model_name="region", name="date_last_updated",),
        migrations.RemoveField(model_name="release", name="date_last_updated",),
        migrations.RemoveField(model_name="theme", name="date_last_updated",),
        migrations.AddField(
            model_name="company", name="date_updated", field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="concept", name="date_updated", field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="franchise", name="date_updated", field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="game", name="date_updated", field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="genre", name="date_updated", field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="platform", name="date_updated", field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="rating", name="date_updated", field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="region", name="date_updated", field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="release", name="date_updated", field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="theme", name="date_updated", field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="company", name="date_added", field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="concept", name="date_added", field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="franchise", name="date_added", field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="game", name="date_added", field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="genre", name="date_added", field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="platform", name="date_added", field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="rating", name="date_added", field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="region", name="date_added", field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="release", name="date_added", field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="theme", name="date_added", field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
