# Generated by Django 3.0.8 on 2020-07-23 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("coreExtend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uuidtaggeditem",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coreextend_uuidtaggeditem_tagged_items",
                to="contenttypes.ContentType",
                verbose_name="content type",
            ),
        ),
        migrations.AlterField(
            model_name="uuidtaggeditem",
            name="object_id",
            field=models.UUIDField(db_index=True, verbose_name="object ID"),
        ),
    ]
