# Generated by Django 2.1.3 on 2018-11-24 10:02

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='coreExtend.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
