# Generated by Django 2.1.3 on 2018-11-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='next_scheduled_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
