# Generated by Django 2.1.3 on 2018-11-19 19:21

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_auto_20181118_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='feed_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_lists', to='aggregator.FeedList'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='feedlist',
            name='can_self_add',
            field=models.BooleanField(choices=[(True, 'Only me'), (False, 'Everyone')], default=True, help_text='Who can edit this list?'),
        ),
    ]
